version: 0.2

phases:
  install:
    commands:
      # install node 14
      - echo installing Node 14...
      - curl -sL https://deb.nodesource.com/setup_15.x | bash -
      - echo curl for nodejs complete
      - apt install -y nodejs
      - echo node installing complete
  pre_build:
    commands:
      # install dependencies
      - echo installing dependencies...
      - npm install
  build:
    commands:
      # build
      - echo building
      - npm run-script build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
  