version: 0.2

phases:
  install:
    commands:
      - echo no install commands
  pre_build:
    commands:
      # install dependencies
      - echo installing dependencies...
      - npm install
  build:
    commands:
      # build
      - echo building
      - npm run-script build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
  